import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {setupGraphics} from './graphics.js';
import {createDriving} from './driving.js';
import {createMotorcycle,buildVehiclePrototypes,motorcycleStyles} from './prototypes/vehicles.js';
import {buildAuto} from './prototypes/auto.js';
import {installCrowd} from './characters.js';
import {createMapDelivery} from './real-map-delivery.js';
import {createMapArt,dressRealMap,createLeafGeometry} from './real-map-art.js';
import {prepareAdventure,munnarHeight,ridingSurfaces} from './munnar-adventure.js';
import {realLocations,prepareRealMap,pointInPolygon,segmentDistance} from './real-map-data.js';

async function start(){
 const requested=new URLSearchParams(location.search).get('location'),id=Object.hasOwn(realLocations,requested)?requested:'kochi',place=realLocations[id];
 const response=await fetch(new URL(`maps/${id}.json`,document.baseURI));if(!response.ok)throw Error('Map snapshot could not load');
 const source=await response.json(),map=prepareRealMap(source),bounds=map.bounds;let adventure=null;if(id==='munnar'){const plan=await fetch(new URL('maps/munnar-adventure.json',document.baseURI));if(!plan.ok)throw Error('Munnar adventure layout could not load');adventure=prepareAdventure(await plan.json(),map)}
 document.querySelector('#place').textContent=place.name;document.querySelector('#description').textContent=place.subtitle;
 document.querySelector('#location').value=id;const header=document.querySelector('header'),orderCard=document.querySelector('#delivery');new ResizeObserver(()=>{orderCard.style.top=`${header.getBoundingClientRect().bottom+8}px`}).observe(header);document.querySelector('#data-link').href=`./maps/${id}.json`;
 const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#real-world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
 renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();scene.background=new THREE.Color(id==='thekkady'?'#bccac0':'#bdd4dd');const fog=new THREE.Fog(scene.background,140,id==='kochi'?700:1100);scene.fog=fog;
 scene.add(new THREE.HemisphereLight('#e6f0f5','#55584b',.95));const sun=new THREE.DirectionalLight('#fff8ee',2.5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:250});sun.shadow.normalBias=.025;sun.shadow.bias=-.00012;scene.add(sun,sun.target);
 const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.2,6000),graphics=setupGraphics(renderer,scene,camera);let detailed=devicePixelRatio<=1.5;graphics.setQuality(detailed);const quality=document.querySelector('#quality');quality.textContent=detailed?'Detail on':'Detail off';quality.setAttribute('aria-pressed',String(detailed));quality.onclick=()=>{detailed=!detailed;graphics.setQuality(detailed);quality.textContent=detailed?'Detail on':'Detail off';quality.setAttribute('aria-pressed',String(detailed));graphics.render()};
 // Heights and scenic planting are deliberately illustrative; OSM X/Z positions stay unchanged.
 const height=(x,z)=>id==='kochi'?0:id==='munnar'?munnarHeight(x,z):12+7*Math.sin(x/380)*Math.cos(z/300);
 const material=(color)=>new THREE.MeshStandardMaterial({color,roughness:.85});
 const art=createMapArt(renderer,id),groundMaterial=art.ground,roadMaterial=art.road,roofMaterials=[art.tile,art.cream,art.tile];
 const reflectionFaces=Array.from({length:6},()=>{const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),gradient=ctx.createLinearGradient(0,0,0,128);gradient.addColorStop(0,'#85aab8');gradient.addColorStop(.55,'#d6e0d8');gradient.addColorStop(1,'#788565');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);return c});scene.environment=new THREE.CubeTexture(reflectionFaces);scene.environment.colorSpace=THREE.SRGBColorSpace;scene.environment.needsUpdate=true;scene.environmentIntensity=.5;
 function batch(geometries,mat){if(!geometries.length)return;const merged=mergeGeometries(geometries);for(const g of geometries)g.dispose();const mesh=new THREE.Mesh(merged,mat);mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);return mesh;}
 const ground=new THREE.PlaneGeometry(bounds.maxX-bounds.minX,bounds.maxZ-bounds.minZ,240,240);ground.rotateX(-Math.PI/2);
 const position=ground.attributes.position;for(let i=0;i<position.count;i++)position.setY(i,height(position.getX(i),position.getZ(i)));ground.computeVertexNormals();const terrain=new THREE.Mesh(ground,groundMaterial);terrain.receiveShadow=true;scene.add(terrain);
 function ribbon(original,width,lift){
  const points=[];for(let i=1;i<original.length;i++){const a=original[i-1],b=original[i],n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/3));for(let j=0;j<n;j++)points.push({x:THREE.MathUtils.lerp(a.x,b.x,j/n),z:THREE.MathUtils.lerp(a.z,b.z,j/n)})}points.push(original.at(-1));
  const vertices=[],indices=[],uv=[];let distance=0;
  points.forEach((p,i)=>{if(i)distance+=Math.hypot(p.x-points[i-1].x,p.z-points[i-1].z);const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],dx=b.x-a.x,dz=b.z-a.z,l=Math.max(.001,Math.hypot(dx,dz));for(const side of [-1,1]){const x=p.x+side*dz/l*width/2,z=p.z-side*dx/l*width/2;vertices.push(x,height(x,z)+lift,z);uv.push((side+1)*width/2,distance)}if(i<points.length-1){const k=i*2;indices.push(k,k+2,k+1,k+1,k+2,k+3);}});
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g;
 }
 batch(map.roads.map(r=>ribbon(r.points,r.width+(id==='kochi'?3:1.8),.045)),art.paving);
 batch(map.roads.map(r=>ribbon(r.points,r.width+.35,.065)),art.cream);
 batch(map.roads.map(r=>ribbon(r.points,r.width,.085)),roadMaterial);
 const paint=[];for(const segment of map.segments.filter(s=>s.width>=6)){const length=Math.hypot(segment.b.x-segment.a.x,segment.b.z-segment.a.z);for(let d=2;d<length-2;d+=6){const a={x:THREE.MathUtils.lerp(segment.a.x,segment.b.x,d/length),z:THREE.MathUtils.lerp(segment.a.z,segment.b.z,d/length)},b={x:THREE.MathUtils.lerp(segment.a.x,segment.b.x,Math.min(d+2.6,length)/length),z:THREE.MathUtils.lerp(segment.a.z,segment.b.z,Math.min(d+2.6,length)/length)};paint.push(ribbon([a,b],.13,.11))}}batch(paint,material('#e4ddc7'));
 if(adventure){for(const surface of ['dirt','gravel']){const trails=adventure.trails.filter(t=>t.surface===surface);batch(trails.map(t=>ribbon(t.points,t.width+1,.07)),material('#97784f'));batch(trails.map(t=>ribbon(t.points,t.width,.10)),art.mat('#ffffff',art.textures[surface]))}}
 if(adventure){const tea=adventure.trails.find(t=>t.id==='tea');batch([ribbon(tea.points.slice(Math.floor(tea.points.length*.40),Math.ceil(tea.points.length*.49)),tea.width,.125)],art.mat('#715744',art.textures.dirt))}
 function polygonShape(points){const s=new THREE.Shape();points.forEach((p,i)=>i?s.lineTo(p.x,-p.z):s.moveTo(p.x,-p.z));s.closePath();return s;}
 const buildingMeshes=roofMaterials.map(()=>[]),roofs=roofMaterials.map(()=>[]);
 for(const b of map.buildings){
  const center=b.points.reduce((p,q)=>({x:p.x+q.x/b.points.length,z:p.z+q.z/b.points.length}),{x:0,z:0}),y=height(center.x,center.z),shape=polygonShape(b.points);
  const walls=new THREE.ExtrudeGeometry(shape,{depth:b.height,bevelEnabled:false});walls.rotateX(-Math.PI/2);walls.translate(0,y,0);const wallUV=walls.attributes.uv,wp=walls.attributes.position;for(let i=0;i<wp.count;i++)wallUV.setXY(i,(wp.getX(i)+wp.getZ(i))*.18,1-(wp.getY(i)-y)/b.height);buildingMeshes[b.id%3].push(walls);
  const roof=new THREE.ShapeGeometry(shape);roof.rotateX(-Math.PI/2);roof.translate(0,y+b.height+.02,0);roofs[b.id%3].push(roof);
  b.bounds={minX:Math.min(...b.points.map(p=>p.x)),maxX:Math.max(...b.points.map(p=>p.x)),minZ:Math.min(...b.points.map(p=>p.z)),maxZ:Math.max(...b.points.map(p=>p.z))};
 }
 buildingMeshes.forEach((g,i)=>batch(g,art.walls[i]));roofs.forEach((g,i)=>batch(g,roofMaterials[i]));
 for(const area of map.areas.filter(a=>a.kind==='water')){const g=new THREE.ShapeGeometry(polygonShape(area.points));g.rotateX(-Math.PI/2);const vertices=g.attributes.position;for(let i=0;i<vertices.count;i++)vertices.setY(i,height(vertices.getX(i),vertices.getZ(i))+.035);g.computeVertexNormals();const mesh=new THREE.Mesh(g,material('#428c98'));mesh.receiveShadow=true;scene.add(mesh);}
 function buildingAt(x,z,radius=0){return map.buildings.some(b=>x>b.bounds.minX-radius&&x<b.bounds.maxX+radius&&z>b.bounds.minZ-radius&&z<b.bounds.maxZ+radius&&(pointInPolygon(x,z,b.points)||b.points.some((p,i)=>segmentDistance(x,z,p,b.points[(i+1)%b.points.length])<radius)));}
 const waterAt=(x,z)=>map.areas.some(a=>a.kind==='water'&&pointInPolygon(x,z,a.points));
 let seed=97;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
 const forestRoads=map.segments.filter(s=>Math.hypot((s.a.x+s.b.x)/2,(s.a.z+s.b.z)/2)<450);
 const trees=[];for(let attempt=0;trees.length<place.trees&&attempt<place.trees*30;attempt++){
  let x=bounds.minX+random()*(bounds.maxX-bounds.minX),z=bounds.minZ+random()*(bounds.maxZ-bounds.minZ);
  if(id==='thekkady'&&trees.length<650&&forestRoads.length){const s=forestRoads[Math.floor(random()*forestRoads.length)],t=random(),dx=s.b.x-s.a.x,dz=s.b.z-s.a.z,length=Math.hypot(dx,dz),offset=(s.width/2+7+random()*22)*(random()<.5?-1:1);x=s.a.x+dx*t+dz/length*offset;z=s.a.z+dz*t-dx/length*offset;}
  const near=map.nearestRoad(x,z);
  if(near.distance<near.segment.width/2+5||buildingAt(x,z,4)||waterAt(x,z))continue;
  trees.push({x,z,y:height(x,z),scale:.8+random()*.7});
 }
 const scenery=dressRealMap({scene,map,id,height,buildingAt,waterAt,trees,art});
 if(adventure){
  const dummy=new THREE.Object3D(),shrubs=[];
  for(let row=0;row<150;row++)for(let col=0;col<175;col++){const x=-870+col*3.7,z=-570+row*4.6+Math.sin(x/65)*4,near=map.nearestRoad(x,z);if(near.distance<near.segment.width/2+2||buildingAt(x,z,2)||waterAt(x,z)||scenery.obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.radius+1.1))continue;shrubs.push({x,z})}
  const tea=new THREE.InstancedMesh(new THREE.SphereGeometry(1,10,6),art.leaves[1],shrubs.length);shrubs.forEach((p,i)=>{dummy.position.set(p.x,height(p.x,p.z)+.55,p.z);dummy.scale.set(1.35,.72,1.05);dummy.updateMatrix();tea.setMatrixAt(i,dummy.matrix)});tea.castShadow=tea.receiveShadow=true;scene.add(tea);
  const nearShrubs=shrubs.filter(p=>adventure.nearestTrail(p.x,p.z).distance<18),teaLeaves=new THREE.InstancedMesh(createLeafGeometry(.65,.16,.16),art.leaves[2],nearShrubs.length*12);let leafIndex=0;
  for(const p of nearShrubs)for(let j=0;j<12;j++){const a=j*2.4;dummy.position.set(p.x+Math.sin(a)*.75,height(p.x,p.z)+.85+(j%3)*.08,p.z+Math.cos(a)*.55);dummy.scale.set(1,1,1);dummy.rotation.set(.25-j%3*.15,a,0);dummy.updateMatrix();teaLeaves.setMatrixAt(leafIndex++,dummy.matrix)}teaLeaves.castShadow=teaLeaves.receiveShadow=true;scene.add(teaLeaves);

  for(const [i,stop]of adventure.stops.entries()){
   const trail=adventure.trails[i],k=Math.floor(trail.points.length*.55),a=trail.points[k-1],b=trail.points[k+1],dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz);let cabin=null;
   for(const side of [-1,1]){const x=stop.x+dz/l*10*side,z=stop.z-dx/l*10*side;if(!buildingAt(x,z,5)&&!waterAt(x,z)){cabin={x,z};break}}if(!cabin)continue;
   const root=new THREE.Group(),y=height(cabin.x,cabin.z);root.position.set(cabin.x,y,cabin.z);root.rotation.y=Math.atan2(stop.x-cabin.x,stop.z-cabin.z);scene.add(root);
   function piece(w,h,d,x,y,z,mat){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;root.add(mesh);return mesh}
   piece(6,3.4,4.5,0,1.7,0,art.walls[i]);piece(6.3,.35,4.8,0,.17,0,art.cream);piece(1.1,2.1,.15,0,1.15,2.3,art.wood);
   for(const x of [-1.9,1.9]){piece(1.35,1.5,.16,x,1.9,2.3,art.wood);piece(1.15,1.3,.025,x,1.9,2.4,art.glass);piece(1.6,.13,.32,x,1.08,2.4,art.cream)}
   const roof=new THREE.Mesh(new THREE.ConeGeometry(1,1,4),art.tile);roof.position.y=4.1;roof.rotation.y=Math.PI/4;roof.scale.set(5,1.7,3.8);roof.castShadow=true;root.add(roof);piece(6.4,.14,1.2,0,2.7,2.7,art.wood);
   for(const x of [-2.8,2.8])piece(.14,2.7,.14,x,1.35,3.1,art.wood);
   scenery.obstacles.push({x:cabin.x,z:cabin.z,radius:4.5});scenery.sign(i===0?'TEA ESTATE COTTAGE':'RIDGE LOOKOUT',cabin.x+Math.sin(root.rotation.y)*2.4,height(cabin.x,cabin.z)+3.05,cabin.z+Math.cos(root.rotation.y)*2.4,4,.55,root.rotation.y,'#765033');
  }
  for(const trail of adventure.trails)for(const p of [trail.points[0],trail.points.at(-1)]){const toward=trail.points[0]===p?trail.points[1]:trail.points.at(-2),dx=toward.x-p.x,dz=toward.z-p.z,l=Math.hypot(dx,dz),x=p.x+dz/l*3.4,z=p.z-dx/l*3.4;scenery.sign(trail.name.toUpperCase(),x,height(x,z)+2.4,z,3.5,.65,Math.atan2(-dx,-dz),'#785134')}
 }
 const player=new THREE.Group(),models=new Map();player.userData.footprint={width:.81,length:2.1};scene.add(player);
 function makeChassis(style){const g=createMotorcycle(style),cargo=new THREE.Mesh(new THREE.BoxGeometry(.60,.52,.55),material(motorcycleStyles[style].color));cargo.position.set(0,1.18,.60);cargo.castShadow=true;g.add(cargo);const labelCanvas=document.createElement('canvas');labelCanvas.width=256;labelCanvas.height=256;const ctx=labelCanvas.getContext('2d');ctx.fillStyle='#cc963f';ctx.fillRect(0,0,256,256);ctx.strokeStyle='#4d452b';ctx.lineWidth=12;ctx.strokeRect(10,10,236,236);ctx.fillStyle='#2f3826';ctx.textAlign='center';ctx.font='bold 42px Arial';ctx.fillText('MUD',128,115);ctx.fillText('MEALS',128,166);const texture=new THREE.CanvasTexture(labelCanvas);texture.colorSpace=THREE.SRGBColorSpace;const label=new THREE.Mesh(new THREE.PlaneGeometry(.48,.42),new THREE.MeshStandardMaterial({map:texture,roughness:.85}));label.position.set(0,1.18,.878);g.add(label);return g;}
 function setModel(style){if(!Object.hasOwn(motorcycleStyles,style))return false;if(!models.has(style))models.set(style,makeChassis(style));if(player.chassis)player.remove(player.chassis);player.chassis=models.get(style);player.add(player.chassis);player.userData.style=style;document.querySelector('#model').value=style;return true;}
 setModel('city');
 const eligible=map.segments.filter(s=>s.width>=5.5),spawnSegments=eligible.length?eligible:map.segments;
 const townSegments=spawnSegments.filter(s=>Math.hypot(s.b.x-s.a.x,s.b.z-s.a.z)>18&&Math.abs((s.a.x+s.b.x)/2)<bounds.maxX-70&&Math.abs((s.a.z+s.b.z)/2)<bounds.maxZ-70),townScore=s=>{const x=(s.a.x+s.b.x)/2,z=(s.a.z+s.b.z)/2;return map.buildings.reduce((score,b)=>{const bx=(b.bounds.minX+b.bounds.maxX)/2,bz=(b.bounds.minZ+b.bounds.maxZ)/2;return score+Math.max(0,1-Math.hypot(x-bx,z-bz)/55)},0)};
 const spawn=id==='kochi'&&townSegments.length?townSegments.reduce((a,b)=>townScore(a)>townScore(b)?a:b):spawnSegments.reduce((a,b)=>segmentDistance(0,0,a.a,a.b)<segmentDistance(0,0,b.a,b.b)?a:b),dx=spawn.b.x-spawn.a.x,dz=spawn.b.z-spawn.a.z,l=Math.hypot(dx,dz);
 const spawnPoint={x:(spawn.a.x+spawn.b.x)/2+dz/l*spawn.width/4,z:(spawn.a.z+spawn.b.z)/2-dx/l*spawn.width/4},spawnHeading=Math.atan2(-dx,-dz);
 const driving=createDriving(),keys=new Set(),touch=new Map();let overview=false,elapsed=0,mapTime=0;
 function clear(){keys.clear();touch.clear();}
 const held=key=>keys.has(key)||[...touch.values()].includes(key);
 addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','SELECT','BUTTON'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','s','a','d'].includes(k)){e.preventDefault();keys.add(k)}});
 addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear()});
 for(const button of document.querySelectorAll('[data-key]')){button.addEventListener('contextmenu',e=>e.preventDefault());button.addEventListener('pointerdown',e=>{touch.set(e.pointerId,button.dataset.key);button.setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>touch.delete(e.pointerId));}
 const people=[];for(const segment of [...map.segments].sort((a,b)=>segmentDistance(spawnPoint.x,spawnPoint.z,a.a,a.b)-segmentDistance(spawnPoint.x,spawnPoint.z,b.a,b.b))){if(people.length>=place.people)break;if(Math.hypot(segment.b.x-segment.a.x,segment.b.z-segment.a.z)<12)continue;const vx=segment.b.x-segment.a.x,vz=segment.b.z-segment.a.z,length=Math.hypot(vx,vz),x=(segment.a.x+segment.b.x)/2+vz/length*(segment.width/2+1.2),z=(segment.a.z+segment.b.z)/2-vx/length*(segment.width/2+1.2);if(buildingAt(x,z,.4)||waterAt(x,z)||scenery.obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.radius+.6))continue;
  const g=new THREE.Group(),placeholder=new THREE.Group();g.position.set(x,height(x,z)+.03,z);g.rotation.y=Math.atan2(-vx,-vz);g.add(placeholder);scene.add(g);const canWalk=Array.from({length:7},(_,i)=>({x:x+vx/length*(i-3),z:z+vz/length*(i-3)})).every(p=>!buildingAt(p.x,p.z,.45)&&!waterAt(p.x,p.z)&&!scenery.obstacles.some(o=>Math.hypot(p.x-o.x,p.z-o.z)<o.radius+.55));people.push({g,standing:{g:placeholder},sitting:null,variant:people.length,home:{x,z},route:canWalk?{x:vx/length,z:vz/length}:null,progress:0,direction:1,wait:people.length*.3,distance:0,walk:0});
 }
 await installCrowd(people,[player]);
 // Small directed graph keeps traffic on the actual OSM roads and respects one-way tags.
 const graph=new Map(),key=p=>p.x.toFixed(3)+','+p.z.toFixed(3);
 for(const s of spawnSegments){for(const p of [s.a,s.b])if(!graph.has(key(p)))graph.set(key(p),{point:p,edges:[]});graph.get(key(s.a)).edges.push({to:key(s.b),width:s.width});if(!s.oneway)graph.get(key(s.b)).edges.push({to:key(s.a),width:s.width});}
 const allStarts=[...graph.keys()].filter(k=>graph.get(k).edges.length),nearStarts=allStarts.filter(k=>{const p=graph.get(k).point;return Math.hypot(p.x-spawnPoint.x,p.z-spawnPoint.z)<220}),starts=id==='kochi'&&nearStarts.length>10?nearStarts:allStarts,prototypes=buildVehiclePrototypes(),auto=buildAuto(),traffic=[];
 function resetTraffic(v,index){for(let attempt=0;attempt<30;attempt++){const from=starts[(index*83+Math.floor(random()*starts.length))%starts.length],node=graph.get(from);v.from=from;v.to=node.edges[0].to;v.width=node.edges[0].width;v.progress=.2+random()*.6;v.speed=0;v.hidden=0;poseTraffic(v,true);const p=v.g.position;if(Math.hypot(p.x-spawnPoint.x,p.z-spawnPoint.z)>v.halfLength+5&&!traffic.some(other=>other!==v&&!other.hidden&&carDistance(p.x,p.z,other)<v.halfLength+2))return;}v.hidden=4;v.g.visible=false;}
 function targetTraffic(v){const a=graph.get(v.from).point,b=graph.get(v.to).point,dx=b.x-a.x,dz=b.z-a.z,length=Math.hypot(dx,dz),offset=v.width/4;return {x:a.x+(b.x-a.x)*v.progress+dz/length*offset,z:a.z+(b.z-a.z)*v.progress-dx/length*offset,heading:Math.atan2(-dx,-dz),length};}
 function poseTraffic(v,snap=false,dt=1/60){const p=targetTraffic(v),target=new THREE.Vector3(p.x,height(p.x,p.z)+.07,p.z);if(snap)v.g.position.copy(target);else v.g.position.lerp(target,1-Math.exp(-12*dt));const turn=THREE.MathUtils.euclideanModulo(p.heading-v.g.rotation.y+Math.PI,Math.PI*2)-Math.PI;v.g.rotation.y+=turn*(snap?1:Math.min(1,dt*6));v.g.visible=!v.hidden;}
 for(let i=0;i<place.traffic;i++){const type=i%11===0&&id==='kochi'?'bus':i%3===0?'auto':i%7===0?'van':'car',g=(type==='auto'?auto:prototypes[type]).clone(true);scene.add(g);const paints=new Map(),palette=['#477c89','#d9d9ca','#a34434','#80885c','#d2b570'];g.traverse(o=>{if(o.material?.userData.surface==='paint'){if(!paints.has(o.material)) {const m=o.material.clone();m.color.set(palette[i%palette.length]);paints.set(o.material,m)}o.material=paints.get(o.material)}});const d=g.userData.bodyDimensions,v={g,type,halfWidth:(d?.width||1.6)/2,halfLength:(d?.length||2.65)/2,wheels:[]};g.traverse(o=>{if(o.userData.wheelRadius)v.wheels.push(o)});traffic.push(v);resetTraffic(v,i);}
 function carDistance(x,z,v){const dx=x-v.g.position.x,dz=z-v.g.position.z,c=Math.cos(v.g.rotation.y),s=Math.sin(v.g.rotation.y);return Math.hypot(Math.max(0,Math.abs(dx*c-dz*s)-v.halfWidth),Math.max(0,Math.abs(dx*s+dz*c)-v.halfLength));}
 function blocked(x,z,heading=player.rotation.y){
  if(x<bounds.minX+2||x>bounds.maxX-2||z<bounds.minZ+2||z>bounds.maxZ-2)return true;
  for(const offset of [-.6,0,.6]){const px=x-Math.sin(heading)*offset,pz=z-Math.cos(heading)*offset;if(buildingAt(px,pz,.45)||scenery.obstacles.some(o=>Math.hypot(px-o.x,pz-o.z)<o.radius+.45)||traffic.some(v=>!v.hidden&&carDistance(px,pz,v)<.45)||people.some(n=>Math.hypot(px-n.g.position.x,pz-n.g.position.z)<.65))return true;
   if(waterAt(px,pz)){const road=map.nearestRoad(px,pz);if(road.distance>road.segment.width/2-.5)return true;}
  }return false;
 }
 let delivery;
 function updateTraffic(dt){for(const [i,v]of traffic.entries()){
  if(v.hidden){v.hidden-=dt;if(v.hidden<=0)resetTraffic(v,i);continue;}
  const p=targetTraffic(v),fx=-Math.sin(v.g.rotation.y),fz=-Math.cos(v.g.rotation.y);let gap=50;
  for(const other of [{position:player.position,halfLength:1},...traffic.filter(o=>o!==v&&!o.hidden).map(o=>({position:o.g.position,halfLength:o.halfLength}))]){const dx=other.position.x-v.g.position.x,dz=other.position.z-v.g.position.z,ahead=dx*fx+dz*fz,side=Math.abs(dx*fz-dz*fx);if(ahead>0&&side<v.halfWidth+.7)gap=Math.min(gap,ahead-v.halfLength-other.halfLength-1.5);}
  const target=gap<1?0:Math.min(id==='kochi'?6:8,Math.sqrt(Math.max(0,gap)*3));v.speed=THREE.MathUtils.damp(v.speed,target,target<v.speed?8:1.4,dt);const advance=Math.min(v.speed*dt,Math.max(0,gap));v.progress+=advance/p.length;
  if(v.progress>=1){const node=graph.get(v.to),choices=node.edges.filter(e=>e.to!==v.from);if(!choices.length){v.hidden=4;v.g.visible=false;continue;}const next=choices[Math.floor(random()*choices.length)];v.from=v.to;v.to=next.to;v.width=next.width;v.progress=0;}
  poseTraffic(v,false,dt);for(const wheel of v.wheels)wheel.rotation.x-=advance/wheel.userData.wheelRadius;
 }}
 const mini=document.querySelector('#minimap'),ctx=mini.getContext('2d');function minimap(){ctx.fillStyle='#78936b';ctx.fillRect(0,0,240,240);const scale=220/Math.max(bounds.maxX-bounds.minX,bounds.maxZ-bounds.minZ),project=p=>[120+p.x*scale,120+p.z*scale];ctx.strokeStyle='#e2dfce';ctx.lineWidth=2;for(const road of map.roads){ctx.beginPath();road.points.forEach((p,i)=>{const a=project(p);i?ctx.lineTo(...a):ctx.moveTo(...a)});ctx.stroke();}if(adventure){for(const [points,color,width]of [[adventure.mainCircuit,'#f4d694',2.5],...adventure.trails.map(t=>[t.points,t.surface==='dirt'?'#ad6737':'#c2a77b',3])]){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>{const q=project(p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke()}}if(delivery?.state.destination&&!delivery.state.finished){const d=project(delivery.state.destination);ctx.fillStyle='#ffd178';ctx.fillRect(d[0]-3,d[1]-3,6,6)}const p=project(player.position);ctx.fillStyle='#ff9e34';ctx.beginPath();ctx.arc(...p,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#122d22';ctx.font='bold 12px system-ui';ctx.fillText('N ↑',9,16);}
 function updateCamera(dt=1,snap=false){scene.fog=overview?null:fog;for(const child of scene.children)if(child.userData.scenicBackdrop)child.visible=!overview;if(overview){const h=Math.max(bounds.maxZ-bounds.minZ,(bounds.maxX-bounds.minX)/camera.aspect)*1.3;camera.position.set(0,h,.01);camera.lookAt(0,0,0);}else{const forward=new THREE.Vector3(-Math.sin(player.rotation.y),0,-Math.cos(player.rotation.y)),target=player.position.clone().addScaledVector(forward,-8-driving.state.speed*.2).add(new THREE.Vector3(0,4.5,0));if(snap)camera.position.copy(target);else camera.position.lerp(target,1-Math.exp(-6*dt));camera.lookAt(player.position.clone().add(new THREE.Vector3(0,1.05,0)).addScaledVector(forward,2));}sun.position.set(player.position.x-40,player.position.y+90,player.position.z+35);sun.target.position.copy(player.position);}
 function reset(){clear();player.position.set(spawnPoint.x,height(spawnPoint.x,spawnPoint.z)+.07,spawnPoint.z);player.rotation.set(0,spawnHeading,0,'YXZ');driving.reset(spawnHeading);elapsed=0;updateCamera(1,true);minimap();document.querySelector('#speed').textContent='0';document.querySelector('#street').textContent=spawn.name||'Local road';document.querySelector('#surface').textContent='Asphalt';}
 function update(dt){if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.1);elapsed+=dt;const throttle=held('w')||held('arrowup')?1:0,brake=held('s')||held('arrowdown')?1:0,steering=Number(held('d')||held('arrowright'))-Number(held('a')||held('arrowleft')),oldHeading=player.rotation.y,fx=-Math.sin(oldHeading),fz=-Math.cos(oldHeading),grade=(height(player.position.x+fx*.4,player.position.z+fz*.4)-height(player.position.x-fx*.4,player.position.z-fz*.4))/.8;
  const surface=adventure?adventure.surfaceAt(player.position.x,player.position.z):ridingSurfaces.asphalt;driving.state.heading=oldHeading;const distance=driving.step(dt,{throttle,brake,steering,grade,wet:surface.wet,speedLimit:surface.speedLimit}),newHeading=driving.state.heading,pieces=Math.max(1,Math.ceil(distance/.2));let moved=0;
  for(let i=1;distance>0&&i<=pieces;i++){const heading=THREE.MathUtils.lerp(oldHeading,newHeading,(i-.5)/pieces),x=player.position.x-Math.sin(heading)*distance/pieces,z=player.position.z-Math.cos(heading)*distance/pieces;if(blocked(x,z,heading)){driving.state.speed=0;driving.state.yawRate=0;driving.state.heading=player.rotation.y;break;}player.position.set(x,height(x,z)+.07,z);player.rotation.y=THREE.MathUtils.lerp(oldHeading,newHeading,i/pieces);moved+=distance/pieces;}
  player.rotation.x=Math.atan(grade);player.rotation.z=driving.state.lean;player.chassis.traverse(o=>{if(o.userData.wheelRadius)o.rotation.x-=moved/o.userData.wheelRadius});
  for(const n of people){let moved=0;n.wait=Math.max(0,n.wait-dt);if(n.route){const angle=Math.atan2(n.route.x*n.direction,n.route.z*n.direction),turn=THREE.MathUtils.euclideanModulo(angle-n.g.rotation.y+Math.PI,Math.PI*2)-Math.PI;n.g.rotation.y+=turn*Math.min(1,dt*5);if(n.wait===0&&Math.abs(turn)<.2){const progress=n.progress+n.direction*dt*.85;if(Math.abs(progress)>3){n.direction*=-1;n.wait=1.1}else{const x=n.home.x+n.route.x*progress,z=n.home.z+n.route.z*progress;if(Math.hypot(x-player.position.x,z-player.position.z)>1.3&&!people.some(o=>o!==n&&Math.hypot(x-o.g.position.x,z-o.g.position.z)<.8)){moved=Math.abs(progress-n.progress);n.progress=progress;n.g.position.set(x,height(x,z)+.03,z)}}}}n.distance+=moved;n.walk=THREE.MathUtils.damp(n.walk,moved>0?1:0,8,dt);n.standing.animate(n.distance*8,elapsed+n.variant,n.walk,n.route?0:n.g.position.distanceTo(player.position)<8?.35:0);}
  updateTraffic(dt);delivery.update(dt,driving.state.speed,surface);updateCamera(dt);mapTime+=dt;if(mapTime>.15){mapTime=0;minimap();document.querySelector('#speed').textContent=String(Math.round(driving.state.speed*3.6));const near=map.nearestRoad(player.position.x,player.position.z);document.querySelector('#street').textContent=near.segment.name||'Local road';document.querySelector('#surface').textContent=surface.name;}
 }
 document.querySelector('#location').onchange=e=>location.assign(`./real-map.html?location=${encodeURIComponent(e.target.value)}`);document.querySelector('#model').onchange=e=>setModel(e.target.value);
 document.querySelector('#view').onclick=()=>{overview=!overview;document.querySelector('#view').textContent=overview?'Follow bike':'Map view';updateCamera(1,true);graphics.render()};document.querySelector('#reset').onclick=reset;
 addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);graphics.resize(innerWidth,innerHeight);updateCamera(1,true);graphics.render()});
 reset();delivery=createMapDelivery({scene,map,player,spawnPoint,height,blocked,id,adventure});await renderer.compileAsync(scene,camera);const clock=new THREE.Clock();
 const app={ready:true,id,source,map,scene,camera,renderer,graphics,player,traffic,people,driving,height,blocked,update,reset,setModel,scenery,delivery,adventure,stats:()=>({roads:map.roads.length,buildings:map.buildings.length,traffic:traffic.length,people:people.length,trees:trees.length,trails:adventure?.trails.length||0,art:scenery.stats})};window.__REAL_MAP__=app;
 document.querySelector('#loading').remove();renderer.setAnimationLoop(()=>{update(Math.min(clock.getDelta(),.1));graphics.render()});
}
start().catch(error=>{console.error('Real map startup failed:',error);window.__REAL_MAP_ERROR__=error.message;const loading=document.querySelector('#loading');loading.classList.add('error');loading.replaceChildren();const title=document.createElement('strong');title.textContent='This location could not load';const detail=document.createElement('p');detail.textContent=error.message;const retry=document.createElement('button');retry.textContent='Retry';retry.onclick=()=>location.reload();const back=document.createElement('a');back.href='./index.html';back.textContent='Return to the village game';loading.append(title,detail,retry,back);});
